upstream curie_postgres {
    server 127.0.0.1:5432;
}

server {
    listen 100.65.42.72:5432;

    allow 100.118.58.111;
    allow 100.86.133.66;
    allow 100.65.42.72;
    deny all;

    proxy_pass curie_postgres;
}
