[client]
toolbarMode = "minimal"

[server]
headless = true
corsAllowedOrigins = [
  "https://ampere-data.work",
  "https://www.ampere-data.work",
]

[browser]
gatherUsageStats = false

[theme]
base = "light"
textColor = "#101723"